name: Build and Deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install Dependencies
        run: npm install

      - name: Delete Old Dist Directory
        run: rm -rf dist

      - name: Create New Dist Directory
        run: mkdir dist

      - name: Install Babel Presets
        run: npm install --save-dev @babel/preset-react

      - name: Make Babel Script Executable
        run: chmod +x node_modules/.bin/babel

      - name: Build with Babel
        run: npx babel src --out-dir dist --presets=@babel/preset-react --config-file ./babel.config.js

      - name: List Files in Dist Directory
        run: ls dist

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add dist
          git commit -m "Update dist directory"

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_GITHUB_TOKEN }}
          publish_dir: ./dist
